name: Make HTML docs

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  docs:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -r requirements.txt
      - name: Sphinx problems report
        uses: ammaraskar/sphinx-problem-matcher@v1
      - name: Build Sphinx docs
        run: |
          cd docs/
          TZ=UTC make html
          sed -i 's/url_root="#"/url_root=""/' _build/html/index.html || true
      - name: Commit documentation changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout --orphan gh-pages
          git rm -rf .
          mv docs/_build/html/* .
          rm -rf __pycache__/ _sources/ docs/
          touch .nojekyll
          git add .
          git commit -a -m "Update documentation"
      - name: Deploy pages
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
